"""Deterministic repository knowledge generation for Codex Forge."""

from __future__ import annotations

import hashlib
import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable


MANAGED_START = "<!-- codex-forge:managed:start -->"
MANAGED_END = "<!-- codex-forge:managed:end -->"
GENERATED_HEADER = "<!-- Generated by Codex Forge. Do not edit manually. -->"
SKIP_PARTS = {".git", ".codex-forge", "__pycache__", "node_modules", "vendor", "target", ".venv"}


def atomic_write(path: Path, content: str) -> bool:
    content = content.rstrip() + "\n"
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.codex-forge.tmp")
    temporary.write_text(content, encoding="utf-8")
    temporary.replace(path)
    return True


def update_managed_block(path: Path, body: str, prefix: str) -> bool:
    block = f"{MANAGED_START}\n{body.rstrip()}\n{MANAGED_END}"
    if not path.exists():
        return atomic_write(path, f"{prefix.rstrip()}\n\n{block}\n")
    current = path.read_text(encoding="utf-8")
    pattern = re.compile(re.escape(MANAGED_START) + r".*?" + re.escape(MANAGED_END), re.S)
    updated = pattern.sub(block, current, count=1) if pattern.search(current) else current.rstrip() + "\n\n" + block
    return atomic_write(path, updated)


def iter_repository_files(root: Path) -> Iterable[Path]:
    for path in sorted(root.rglob("*")):
        if not path.is_file() or any(part in SKIP_PARTS for part in path.relative_to(root).parts):
            continue
        if path.name.endswith(".codex-forge.tmp") or path.is_relative_to(root / "docs" / "generated"):
            continue
        yield path


def source_hash(root: Path) -> str:
    digest = hashlib.sha256()
    for path in iter_repository_files(root):
        digest.update(path.relative_to(root).as_posix().encode())
        try:
            digest.update(path.read_bytes())
        except OSError:
            continue
    return digest.hexdigest()[:16]


def detect_stack(root: Path) -> list[str]:
    markers = {
        "Python": ("pyproject.toml", "setup.py", "requirements.txt"),
        "Node.js": ("package.json",),
        "Go": ("go.mod",),
        "Rust": ("Cargo.toml",),
        "Java": ("pom.xml", "build.gradle", "build.gradle.kts"),
    }
    detected = [name for name, files in markers.items() if any((root / item).exists() for item in files)]
    if "Python" not in detected and any(path.suffix == ".py" for path in iter_repository_files(root)):
        detected.append("Python")
    return detected


def verification_commands(root: Path) -> list[str]:
    if (root / "go.mod").exists():
        return ["go test ./..."]
    if (root / "Cargo.toml").exists():
        return ["cargo test"]
    if (root / "package.json").exists():
        try:
            scripts = json.loads((root / "package.json").read_text(encoding="utf-8")).get("scripts", {})
        except (OSError, json.JSONDecodeError):
            scripts = {}
        for name in ("test", "check", "typecheck"):
            if name in scripts:
                return [f"npm run {name}"]
        return []
    if (root / "tests").is_dir():
        return ["python3 -m unittest discover -s tests"]
    return []


def repository_map(root: Path) -> str:
    groups: dict[str, list[str]] = {}
    for path in iter_repository_files(root):
        relative = path.relative_to(root).as_posix()
        top = relative.split("/", 1)[0] if "/" in relative else "(root)"
        groups.setdefault(top, []).append(relative)
    lines = [GENERATED_HEADER, "# Repository Map", "", f"Source hash: `{source_hash(root)}`", ""]
    for group, paths in sorted(groups.items()):
        lines.extend((f"## {group}", "", *(f"- `{path}`" for path in paths), ""))
    return "\n".join(lines)


def verification_map(root: Path) -> str:
    commands = verification_commands(root)
    lines = [GENERATED_HEADER, "# Verification Map", "", f"Source hash: `{source_hash(root)}`", "", "## Commands", ""]
    lines.extend(f"- `{command}`" for command in commands)
    if not commands:
        lines.append("- No deterministic verification command detected.")
    lines.extend(("", "## Detection", "", "Commands are selected from repository-native build markers and package scripts."))
    return "\n".join(lines)


def doc_title(path: Path) -> str:
    try:
        match = re.search(r"^#\s+(.+)$", path.read_text(encoding="utf-8"), re.M)
    except OSError:
        return path.stem
    return match.group(1).strip() if match else path.stem


def build_index(directory: Path, title: str) -> str:
    entries = [path for path in sorted(directory.glob("*.md")) if path.name != "index.md"]
    lines = [GENERATED_HEADER, f"# {title}", ""]
    lines.extend(f"- [{doc_title(path)}](./{path.name})" for path in entries)
    if not entries:
        lines.append("- No documents yet.")
    return "\n".join(lines)


def architecture_block(root: Path) -> str:
    stacks = detect_stack(root)
    directories = sorted(path.name for path in root.iterdir() if path.is_dir() and path.name not in SKIP_PARTS)
    return "\n".join(
        (
            "## Automatically observed repository facts",
            "",
            f"- Detected stack: {', '.join(stacks) if stacks else 'not yet detected'}",
            f"- Top-level directories: {', '.join(f'`{name}/`' for name in directories) if directories else 'none'}",
            "- Generated repository and verification knowledge lives under `docs/generated/`.",
        )
    )


def bootstrap(root: Path) -> list[Path]:
    changed: list[Path] = []
    agents_body = """## Knowledge routes

- Architecture and boundaries: `ARCHITECTURE.md`
- Durable design: `docs/design-docs/index.md`
- Current product behavior: `docs/product-specs/index.md`
- Complex task execution: `docs/exec-plans/active/`
- Verification entry: `docs/generated/verification-map.md`

## Workflow entry

Codex Forge classifies every task automatically. Lightweight tasks execute directly; standard and large tasks use an automatically maintained ExecPlan. Never hand-edit `docs/generated/`."""
    if update_managed_block(root / "AGENTS.md", agents_body, "# Repository Agent Guide"):
        changed.append(root / "AGENTS.md")
    if update_managed_block(root / "ARCHITECTURE.md", architecture_block(root), "# Architecture"):
        changed.append(root / "ARCHITECTURE.md")
    defaults = {
        root / "docs" / "design-docs" / "core-beliefs.md": """# Core Beliefs

- The repository is the durable knowledge base.
- Prefer verified facts over repeated rediscovery.
- Keep generated facts deterministic and human design knowledge intentional.
""",
        root / "docs" / "PLANS.md": """# ExecPlan Standard

Create no plan for lightweight tasks. Create one active plan for standard or large tasks and keep its Progress, Discoveries, Decisions, Validation, and Outcomes current. Archive it only after verification passes.
""",
    }
    for path, content in defaults.items():
        if not path.exists() and atomic_write(path, content):
            changed.append(path)
    for directory in (
        root / "docs" / "exec-plans" / "active",
        root / "docs" / "exec-plans" / "completed",
        root / "docs" / "product-specs",
        root / "docs" / "generated",
    ):
        directory.mkdir(parents=True, exist_ok=True)
    return changed + refresh(root)


def refresh(root: Path) -> list[Path]:
    changed: list[Path] = []
    if update_managed_block(root / "ARCHITECTURE.md", architecture_block(root), "# Architecture"):
        changed.append(root / "ARCHITECTURE.md")
    indexes = {
        root / "docs" / "design-docs" / "index.md": build_index(root / "docs" / "design-docs", "Design Documents"),
        root / "docs" / "product-specs" / "index.md": build_index(root / "docs" / "product-specs", "Product Specifications"),
    }
    for path, content in indexes.items():
        if atomic_write(path, content):
            changed.append(path)
    generated = {
        root / "docs" / "generated" / "repository-map.md": repository_map(root),
        root / "docs" / "generated" / "verification-map.md": verification_map(root),
    }
    for path, content in generated.items():
        if atomic_write(path, content):
            changed.append(path)
    return changed


def check_stale(root: Path, active_days: int = 14) -> list[str]:
    issues: list[str] = []
    expected = repository_map(root).rstrip() + "\n"
    path = root / "docs" / "generated" / "repository-map.md"
    if not path.exists() or path.read_text(encoding="utf-8") != expected:
        issues.append("generated repository map is stale")
    cutoff = datetime.now(timezone.utc).timestamp() - active_days * 86400
    for plan in (root / "docs" / "exec-plans" / "active").glob("*.md"):
        if plan.stat().st_mtime < cutoff:
            issues.append(f"active plan is older than {active_days} days: {plan.relative_to(root)}")
    link_pattern = re.compile(r"\[[^]]*]\((?!https?://|#)([^)#]+)(?:#[^)]*)?\)")
    for document in iter_repository_files(root):
        if document.suffix != ".md":
            continue
        try:
            links = link_pattern.findall(document.read_text(encoding="utf-8"))
        except OSError:
            continue
        for link in links:
            if not (document.parent / link).resolve().exists():
                issues.append(f"broken link in {document.relative_to(root)}: {link}")
    return sorted(set(issues))
